context.objects = [
    {   factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = waybar_mic
            node.description = "Waybar Recording - Mic"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
            node.driver      = true
        }
    }
    {   factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = waybar_snd
            node.description = "Waybar Recording - Snd"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
            node.driver      = true
        }
    }
]
